export const defaultItems = [
  {
    id: 1,
    name: "Sobre mí",
    row: 1,
    col: 1,
    prevRow: 2,
    prevCol: 1,
    icon: "📁",
    selected: false,
  },
  {
    id: 2,
    name: "Experiencia laboral",
    row: 2,
    col: 1,
    prevRow: 3,
    prevCol: 1,
    icon: "https://img.icons8.com/?size=100&id=GzCW12vGkSHM&format=png&color=000000",
    selected: false,
  },
  {
    id: 3,
    name: "Habilidades",
    row: 3,
    col: 1,
    prevRow: 4,
    prevCol: 1,
    icon: "⚙️",
    selected: false,
  },
  {
    id: 4,
    name: "Proyectos",
    row: 4,
    col: 1,
    prevRow: 5,
    prevCol: 1,
    icon: "https://img.icons8.com/?size=100&id=9OGIyU8hrxW5&format=png&color=000000",
    selected: false,
  },
  {
    id: 5,
    name: "Educación",
    row: 5,
    col: 1,
    prevRow: 6,
    prevCol: 1,
    icon: "https://img.icons8.com/?size=100&id=7LhMaNDFgoYK&format=png&color=000000",
    selected: false,
  },
  {
    id: 6,
    name: "Contacto",
    row: 6,
    col: 1,
    prevRow: 7,
    prevCol: 1,
    icon: "📞",
    selected: false,
  },
  // Agrega más elementos por defecto aquí
];
